"""add chat and pdf models

Revision ID: c39683f33e4e
Revises: 3b463f4c3ef9
Create Date: 2024-12-11 21:07:35.788451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39683f33e4e'
down_revision: Union[str, None] = '3b463f4c3ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_upload',
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('file', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdf_upload')),
    sa.UniqueConstraint('id', name=op.f('uq_pdf_upload_id'))
    )
    op.create_index(op.f('ix_pdf_upload_path'), 'pdf_upload', ['path'], unique=True)
    op.create_table('ai_message',
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('additional_kwargs', sa.JSON(), nullable=False),
    sa.Column('response_metadata', sa.JSON(), nullable=False),
    sa.Column('usage_metadata', sa.JSON(), nullable=False),
    sa.Column('pdf_upload_id', sa.UUID(), nullable=False),
    sa.Column('user_message', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pdf_upload_id'], ['pdf_upload.id'], name=op.f('fk_ai_message_pdf_upload_id_pdf_upload')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_message')),
    sa.UniqueConstraint('id', name=op.f('uq_ai_message_id'))
    )
    op.create_table('pdf_content',
    sa.Column('page_content', sa.String(), nullable=False),
    sa.Column('pdf_metadata', sa.JSON(), nullable=False),
    sa.Column('pdf_upload_id', sa.UUID(), nullable=False),
    sa.Column('content_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pdf_upload_id'], ['pdf_upload.id'], name=op.f('fk_pdf_content_pdf_upload_id_pdf_upload')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdf_content')),
    sa.UniqueConstraint('id', name=op.f('uq_pdf_content_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_content')
    op.drop_table('ai_message')
    op.drop_index(op.f('ix_pdf_upload_path'), table_name='pdf_upload')
    op.drop_table('pdf_upload')
    # ### end Alembic commands ###
